name: My First workflow 

on: push

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v6

        - name: Welcome message
          run: echo "My first github actions job"
          
        - name: List files
          run: ls 

        - name: Read the file
          run: cat README.md