name: My workflow1
on: push
jobs:
	firstjob: 
		runs-on: ubuntu-latest
		steps:
		- name: Check-repo
		  uses: actions/checkout@v6
	
		- name: List read files
		  run: |
	        echo "My github action job"
		    ls -ltra
		    cat README.md
		
		- name: Generate ASCII artbook
	      run: cowsay -f dragon "Run for cover, I am a dragon. RRWWR" >> dragon.txt

