name: My First workflow 

on: push

jobs:
    firstjob: 
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v6

        - name: List repos
          run: ls -ltra
        
        - name: Executing shell script
          run: |
           chmod +x ascii-generate.sh
           ./ascii-generate.sh
