name: My multi workflow 

on: push

jobs:
  build_job_1: 

    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a dragon. RRWWR" >> dragon.txt

    - uses: actions/upload-artifact@v4
      with:
        name: dragon-txt
        path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: dragon-txt

    - name: Test file exists
      run: |
        ls -l
        grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: dragon-txt 
        
    
    - name: Read the file content
      run: cat dragon.txt

    - name: deploy
      run: echo Deploying ... .. ..