# name: Using matrix
# on: 
#   push:
#   workflow_dispatch: 

# jobs:
#   deploy-on-ubuntu:
#     runs-on: ubuntu-latest
#     steps:
#     - name: ECHO docker details
#       run: docker info

#     - name: Run Images
#       run: docker run hello-world

#   deploy-on-windows:
#     runs-on: windows-latest
#     steps:
#     - name: ECHO docker details
#       run: docker info

#     - name: Run Images 
#       # run: docker run hello-world

# # using matrix with diff OS and images
# name: Using matrix
# on: 
#   push:
#   workflow_dispatch: 

# jobs:
#   deploy:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, ubuntu-20.04, windows-latest]
#         images: [hello-world, alpine]
#     runs-on: ${{ matrix.os}}
#     steps:
#     - name: ECHO docker details
#       run: docker info

#     - name: Run Images ${{ matrix.os}}
#       run: docker run ${{ matrix.images}}
      
# using matrix with diff OS and images, with include/excludes
name: Using matrix
on: 
  push:
  workflow_dispatch: 

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.04
            
    runs-on: ${{ matrix.os}}
    steps:
    - name: ECHO docker details
      run: docker info

    - name: Run Images ${{ matrix.os}}
      run: docker run ${{ matrix.images}}
      