name: Using matrix
on: 
  push:
  workflow_dispatch: 

jobs:
  deploy-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: ECHO docker details
      run: docker info

    - name: Run Images
      run: docker run images

  deploy-on-windows:
    runs-on: windows-latest
    steps:
    - name: ECHO docker details
      run: docker info

    - name: Run Images
      run: docker run images